
#ifndef LINUX_2021SPRING_CONSTANTS_H
#define LINUX_2021SPRING_CONSTANTS_H

#define BLOCK_SIZE 4096
#define BYTES_FOR_INODE_NUMBER 8
#define BYTES_FOR_NAME (256 - BYTES_FOR_INODE_NUMBER - 1)
#define ENTRY_SIZE 256
#define INODE_DIRECT_MAPPING 12
#define INODE_INDIRECT_MAPPING_1 3
#define INODE_MAPPING_SIZE (INODE_DIRECT_MAPPING + INODE_INDIRECT_MAPPING_1)
#define INODE_SIZE (INODE_MAPPING_SIZE * 8 + 8)
#define INODES_PER_BLOCK (BLOCK_SIZE / INODE_SIZE)
#define MAX_SIZE (1ul << 30)
#define IMAP_BLOCKS 1
#define BMAP_BLOCKS 8
#define MAP_BLOCKS (IMAP_BLOCKS + BMAP_BLOCKS)
#define INODES_BLOCKS 4096
#define NUMBER_OF_EMPTY_BLOCKS 1
#define FIRST_DATA_BLOCK_OFFSET (1 + MAP_BLOCKS + INODES_BLOCKS + NUMBER_OF_EMPTY_BLOCKS)
#define ENTRIES_PER_BLOCK (BLOCK_SIZE / ENTRY_SIZE)
#define ROOT_INODE_INDEX 1

#define FOLDER_ATTR 1
#define FILE_ATTR 0

//#define DEBUG_

#define FILESYSTEM_FILE "filesystem"
#endif //LINUX_2021SPRING_CONSTANTS_H
